# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "991ca58759578115f1c656f50326cd4344656153a8235c63894e03adb21d8089"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9b80268e69e1eb96f8d8f884aa59185d72546d1b6ec8a74298ad3baaf5a405e"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ea9439b3d65e5da956a8f5761dba060914f965a4c13b61951f3d668b0a7e1a2d"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6bf4b92fb0c1390c58a8a161b257047b72e0a8060ea0d9d54b7f5fb8f0a3c7dc"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/candy-tools/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required
end
